defaults:
  - encoder: r3m
  - reward: latent
  - agent: sac
  - replay_buffer: default
  - env: libero_arm
  - wandb: default
  - goals: goals_arm
  - _self_

seed: 42
device: cuda

output_dir: ${hydra:runtime.output_dir}
checkpoint_dir: ${hydra:runtime.output_dir}/checkpoints
checkpoint_freq: 100000        # save every N env steps

training:
  total_env_steps: 300

eval:
  eval_freq: 100               # eval every N env steps
  eval_episodes: 1

# logging
log_level: INFO               # DEBUG, INFO, WARNING, ERROR

