# @package _global_.env
name: libero
object_name: milk             # MuJoCo object name (must exist in LIBERO assets)
#task_suite: libero_spatial    # libero_spatial | libero_object | libero_goal | libero_10
#task_id: 0
camera_heights: 224
camera_widths: 224
camera_name: agentview        # agentview | robot0_eye_in_hand
action_dim: 7                 # 6 DoF EEF delta + 1 gripper
episode_length: 300           # max steps per episode
success_threshold: 0.1        # distance threshold for success (metres)
