# @package _global_.encoder
name: vae
camera_key: agentview_image

# VAE architecture
encoder_channels: [32, 64, 128, 256]
decoder_channels: [256, 128, 64, 32]
# training
vae_lr: 1.0e-3
vae_batch_size: 128
vae_train_freq: 3000         # retrain every N env steps
vae_train_steps: 200         # gradient steps per retraining
freeze: false                # VAE is trained online

# NEW
representation_size: 4
beta: 0.08
num_epochs: 501
decoder_activation: sigmoid
batch_size: 128
lr: 1e-3
log_level: INFO               # DEBUG, INFO, WARNING, ERROR
imsize: 48  # Target size for VAE
channels: 3
vae_path: vae_models/model_epoch_900.pth  # Path to pre-trained VAE model (for loading during policy training)